apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: argocd
subjects:
  - kind: Service
    name: argocd-server
    spec:
      protocol: http
      target: http://argocd-server.argocd.svc.cluster.local
tunnelRef:
  kind: ClusterTunnel
  name: lab
  disableDNSUpdates: false
