apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: OriginIssuer
metadata:
  name: cf-origin-issuer
spec:
  requestType: OriginECC
  auth:
    tokenRef:
      name: cf-api-token-secret
      key: key
