apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: avelin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/avelinapp/iac.git"
    targetRevision: "main"
    path: "k8s"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: avelin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
